### PR TITLE
update code to new font awesome version 5.10.2

### PR DESCRIPTION
**Pull request by mbsanchez**
I've udpated QtAwesome to new font awesome 5.10.2, including support for Free and Pro modes, however the pro font files are not including due to license limitations. Nevertheless, users with pro license can include the font files and use them easily.

### CODE REVIEW

**Comment by mbsanchez** [comment]
I've also changed the sample application in order to show all the icons in a listview, as show below:

Free Solid Icons
free-solid

Free Regular Icons
free-regular

Free-Brands Icons
free-brands

Pro-Solid Icons:
pro-solid

Pro-Regular Icons:
pro-regular

Pro-Light Icons:
pro-light

Pro-Duotone Icons:
pro-duotone

**Comment by gamecreature** [comment]
Hi @mbsanchez, I will check this out next week. It looks very promising! Thanks for the PR!

**Comment by gamecreature** [comment]
Hi I'm trying to merge this, but it looks like something is not right. (
The free version of fontawesome contains a 'beer' icon for the solid icons.
When I look at the example there's any beer icon. Many of the icons are not there

image

**Comment by gamecreature** [comment]
BTW. I fixed an issue that compilation failed when defining the free-version. 
It seem I didn't updated the PR, but created a new branch (mbsanchez-master)

**Comment by mbsanchez** [comment]
It seems that the font was not set correctly, can you see regular and brand icons correctly.

I've clonned the mbsanchez-master branch and I've built on my side, and the application shows the icons correctly for all styles.

Did you build on linux, windows or mac?

**Comment by mbsanchez** [comment]
I've run the app on linux and i've got the issue, it appears that the font family is same for font regular and font solid. I'm trying to fix

**Comment by mbsanchez** [comment]
I've fixed the issue, let me update the pull request.

**Comment by mbsanchez** [comment]
@gamecreature can you check? I fixed the issue on linux, it was due to font family and font weight, in linux the font family is same for regular and solid, but we need to set the proper font weight in order to show the icons correctly.

**Comment by gamecreature** [comment]
@mbsanchez Thanks for your fixes! It looks like it's working now.
I've created a fontawesome-5 branch for now. I will test-drive this, and will merge it to master later.
Thank you very much for you contribution!

**Pull request closed without merging**
